# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth_Stones',
            fields=[
                ('stone_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stone_month', models.IntegerField(choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')])),
                ('stone_photo', models.ImageField(max_length=255, null=True, upload_to=b'static/images/birth_stones')),
                ('description', models.TextField()),
                ('cleaning_tips', models.TextField()),
            ],
            options={
                'verbose_name': 'Birth Stone',
                'verbose_name_plural': 'Birth Stones',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
