# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20170518_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth_stones',
            name='stone_photo',
            field=models.ImageField(max_length=255, null=True, upload_to=b'designs/static/images/birth_stones'),
        ),
    ]
