# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_auto_20170518_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premier_Brands',
            fields=[
                ('brand_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brand_main_photo', models.ImageField(max_length=255, null=True, upload_to=b'designs/static/images/premier_brands/brand_main_photo')),
                ('brand_logo', models.ImageField(max_length=255, null=True, upload_to=b'designs/static/images/premier_brands/brand_logo')),
                ('brand_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Premier Brand',
                'verbose_name_plural': 'Premier Brands',
            },
        ),
    ]
