# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_premier_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('client_query', models.TextField(max_length=1001)),
                ('sent_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Query',
                'verbose_name_plural': 'Client Queries',
            },
        ),
    ]
