# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_auto_20170531_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_arrival_name', models.CharField(max_length=255)),
                ('new_arrival_photo', models.ImageField(max_length=255, upload_to=b'designs/static/images/new_arrivals')),
                ('new_arrival_description', models.TextField(max_length=1001)),
                ('image_position', models.CharField(choices=[(b'right', b'right'), (b'left', b'left')], max_length=5)),
            ],
            options={
                'verbose_name': 'New Arrival',
                'verbose_name_plural': 'New Arrivals',
            },
        ),
        migrations.AlterField(
            model_name='premier_brands',
            name='brand_description',
            field=models.TextField(max_length=1001),
        ),
    ]
