# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_auto_20170808_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrivals',
            name='image_position',
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
