# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_auto_20170809_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255)),
                ('slide_image', models.ImageField(max_length=255, upload_to=b'designs/static/images/sildes')),
                ('slide_for', models.CharField(choices=[(b'Home Page', b'Home Page'), ('Hamilton', 'Hamilton'), ('Longines', 'Longines'), ('Tissot', 'Tissot')], max_length=255)),
            ],
        ),
    ]
