# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_carouselslides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselslides',
            options={'verbose_name': 'Carousel Slide', 'verbose_name_plural': 'Carousel Slides'},
        ),
        migrations.AddField(
            model_name='carouselslides',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
