# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_auto_20170809_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslides',
            name='first_slide',
            field=models.BooleanField(default=False),
        ),
    ]
