# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0013_carouselslides_first_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselSlides',
        ),
    ]
