# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0017_carouselslides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselslides',
            name='slide_name',
            field=models.CharField(max_length=255),
        ),
    ]
