# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0018_auto_20170810_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_main_image', models.ImageField(max_length=255, upload_to='designs/static/images/services/main')),
                ('service_description', models.TextField(max_length=1001)),
                ('service_second_image', models.ImageField(max_length=255, upload_to='designs/static/images/services/second')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.AlterField(
            model_name='birth_stones',
            name='stone_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='birth_stones',
            name='stone_photo',
            field=models.ImageField(max_length=255, null=True, upload_to='designs/static/images/birth_stones'),
        ),
        migrations.AlterField(
            model_name='carouselslides',
            name='slide_for',
            field=models.CharField(choices=[('Home Page', 'Home Page'), ('Hamilton', 'Hamilton'), ('Longines', 'Longines'), ('Tissot', 'Tissot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='carouselslides',
            name='slide_image',
            field=models.ImageField(max_length=255, upload_to='designs/static/images/sildes'),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='new_arrival_photo',
            field=models.ImageField(max_length=255, upload_to='designs/static/images/new_arrivals'),
        ),
        migrations.AlterField(
            model_name='premier_brands',
            name='brand_logo',
            field=models.ImageField(max_length=255, null=True, upload_to='designs/static/images/premier_brands/brand_logo'),
        ),
        migrations.AlterField(
            model_name='premier_brands',
            name='brand_main_photo',
            field=models.ImageField(max_length=255, null=True, upload_to='designs/static/images/premier_brands/brand_main_photo'),
        ),
    ]
